[font]
normal.family = "3270 Nerd Font Mono"
normal.style = "Regular"
bold.family = "3270 Nerd Font Mono"
bold.style = "Bold"
italic.family = "3270 Nerd Font Mono"
italic.style = "Italic"
bold_italic.family = "3270 Nerd Font Mono"
bold_italic.style = "Bold Italic"

size = 15.0